// =========================================================================
// PDF 1: English Vocabulary with Pronunciation & Bengali Meaning (Complete)
// =========================================================================
const pdf1Data = [
    // Page 1: Education & Environment
    [
        { w: "Tertiary education", ipa: "TUR-shuh-ree ej-oo-KAY-shun", bn: "উচ্চশিক্ষা (বিশ্ববিদ্যালয় বা সমমানের শিক্ষা)" },
        { w: "Argue", ipa: "AR-gyoo", bn: "যুক্তি দেওয়া / দাবি করা" },
        { w: "Bear the costs", ipa: "bair thuh kosts", bn: "ব্যয় বা খরচ বহন করা" },
        { w: "Equality of opportunity", ipa: "i-KWOL-i-tee uv op-ur-TYOO-ni-tee", bn: "সুযোগের সমতা" },
        { w: "Funded", ipa: "FUN-did", bn: "অর্থায়িত / সরকারি অনুদানপ্রাপ্ত" },
        { w: "Disadvantaged backgrounds", ipa: "dis-ud-VAN-tijd BAK-growndz", bn: "সুবিধাবঞ্চিত বা পিছিয়ে পড়া পটভূমি" },
        { w: "Deterred", ipa: "di-TURD", bn: "নিরুৎসাহিত / বাধাপ্রাপ্ত" },
        { w: "Prospect", ipa: "PROS-pekt", bn: "সম্ভাবনা / প্রত্যাশা" },
        { w: "Incurring debts", ipa: "in-KUR-ing dets", bn: "বিপুল ঋণের সম্মুখীন হওয়া / দেনায় জড়ানো" },
        { w: "Capable", ipa: "KAY-puh-bul", bn: "সক্ষম / যোগ্য" },
        { w: "Full potential", ipa: "fool puh-TEN-shul", bn: "পূর্ণ সম্ভাবনা বা সামর্থ্য" },
        { w: "Restricted", ipa: "ri-STRIK-tid", bn: "সীমাবদ্ধ / বাধাপ্রাপ্ত" },
        { w: "Financial circumstances", ipa: "fye-NAN-shul SUR-kum-stan-siz", bn: "আর্থিক অবস্থা বা পরিস্থিতি" },
        { w: "Highly skilled workforce", ipa: "HYE-lee skild WURK-forss", bn: "অত্যন্ত দক্ষ কর্মীবাহিনী" },
        { w: "Significantly", ipa: "sig-NIF-i-kunt-lee", bn: "উল্লেখযোগ্যভাবে / ব্যাপকভাবে" },
        { w: "Contribute", ipa: "kun-TRIB-yoot", bn: "অবদান রাখা / অংশ দেওয়া" },
        { w: "Taxpayers", ipa: "TAKS-pay-urz", bn: "করদাতা" },
        { w: "Foot the bill", ipa: "foot thuh bil", bn: "সম্পূর্ণ খরচ মেটানো / বিল পরিশোধ করা" },
        { w: "Financial burden", ipa: "fye-NAN-shul BUR-dun", bn: "আর্থিক বোঝা" },
        { w: "Reduction", ipa: "ri-DUK-shun", bn: "হ্রাস / কমানো" },
        { w: "Essential public services", ipa: "i-SEN-shul PUB-lik SUR-vi-siz", bn: "অত্যাবশ্যকীয় জনসেবা" },
        { w: "Denied access", ipa: "di-NYDE AK-sess", bn: "প্রবেশাধিকার বা সুযোগ থেকে বঞ্চিত হওয়া" },
        { w: "Lack of funds", ipa: "lak uv fundz", bn: "তহবিলের অভাব / অর্থের অভাব" },
        { w: "Income threshold", ipa: "IN-kum THRESH-hohld", bn: "আয়ের নির্দিষ্ট সীমা" },
        { w: "Equitable", ipa: "EK-wi-tuh-bul", bn: "ন্যায়সঙ্গত / পক্ষপাতহীন" },
        { w: "Sustainable", ipa: "suh-STAY-nuh-bul", bn: "টেকসই / দীর্ঘস্থায়ী" },
        { w: "Income-contingent", ipa: "IN-kum kun-TIN-junt", bn: "আয়-সাপেক্ষ / আয়ের ওপর নির্ভরশীল" }
    ],
    // Page 2: Environment & Plastic Pollution
    [
        { w: "Pressing environmental issues", ipa: "PRES-ing in-vye-run-MEN-tul ISH-ooz", bn: "জরুরি/উদ্বেগজনক পরিবেশগত সমস্যা" },
        { w: "Rampant production", ipa: "RAM-punt pruh-DUK-shun", bn: "অনিয়ন্ত্রিত বা ব্যাপক উৎপাদন" },
        { w: "Disposal", ipa: "dis-POH-zul", bn: "বর্জ্য হিসেবে ফেলে দেওয়া / নিষ্পত্তি" },
        { w: "Ecosystems", ipa: "EE-koh-sis-tumz", bn: "বাস্তুতন্ত্র / প্রতিবেশ ব্যবস্থা" },
        { w: "Phenomenon", ipa: "fi-NOM-uh-non", bn: "ঘটনা / বিষয়" },
        { w: "Viable solutions", ipa: "VYE-uh-bul suh-LOO-shunz", bn: "বাস্তবসম্মত বা কার্যকর সমাধান" },
        { w: "Mitigate", ipa: "MIT-i-gayt", bn: "প্রশমিত করা / কমানো / তীব্রতা হ্রাস করা" },
        { w: "Widespread use", ipa: "WYDE-spred yooss", bn: "ব্যাপক ব্যবহার" },
        { w: "Single-use items", ipa: "SING-gul yooss EYE-tumz", bn: "একবার ব্যবহারযোগ্য জিনিসপত্র" },
        { w: "Incredibly durable", ipa: "in-KRED-uh-blee DYOOR-uh-bul", bn: "অবিশ্বাস্যভাবে টেকসই" },
        { w: "Consequently", ipa: "KON-si-kwunt-lee", bn: "ফলস্বরূপ / পরিণতিতে" },
        { w: "Decompose", ipa: "dee-kum-POHZ", bn: "পচে যাওয়া / পচনশীল হওয়া" },
        { w: "Throwaway culture", ipa: "THROH-uh-way KUL-chur", bn: "একবার ব্যবহার করে ফেলে দেওয়ার সংস্কৃতি" },
        { w: "Discarded", ipa: "dis-KAR-did", bn: "পরিত্যক্ত / ফেলে দেওয়া হয়েছে এমন" },
        { w: "Landfills", ipa: "LAND-filz", bn: "ময়লা ফেলার নির্ধারিত জায়গা / ভাগাড়" },
        { w: "Inadequate", ipa: "in-AD-i-kwut", bn: "অপর্যাপ্ত" },
        { w: "Exacerbate", ipa: "ig-ZAS-ur-bayt", bn: "আরও খারাপ করা / অবনতি ঘটানো" },
        { w: "Concerted actions", ipa: "kun-SUR-tid AK-shunz", bn: "সম্মিলিত বা ঐক্যবদ্ধ পদক্ষেপ" },
        { w: "Intervene", ipa: "in-tur-VEEN", bn: "হস্তক্ষেপ করা" },
        { w: "Implementing strict regulations", ipa: "IM-pli-men-ting strikt reg-yuh-LAY-shunz", bn: "কঠোর নিয়মকানুন প্রয়োগ করা" },
        { w: "Biodegradable alternatives", ipa: "bye-oh-di-GRAY-duh-bul awl-TUR-nuh-tivz", bn: "প্রাকৃতিকভাবে পচনশীল বিকল্প" },
        { w: "Conventional", ipa: "kun-VEN-shuh-nul", bn: "গতানুগতিক / প্রচলিত" },
        { w: "Substitute", ipa: "SUB-sti-tyoot", bn: "বিকল্প বস্তু" },
        { w: "Ubiquitous use", ipa: "yoo-BIK-wi-tus yooss", bn: "সর্বব্যাপী বা সর্বত্র ব্যবহার" },
        { w: "Stringent", ipa: "STRIN-junt", bn: "অত্যন্ত কঠোর" },
        { w: "Eco-friendly", ipa: "EE-koh FREND-lee", bn: "পরিবেশবান্ধব" }
    ],
    // Page 3: Technology, Relationships, Health & Lifestyle
    [
        { w: "Technological advancements", ipa: "tek-nuh-LOJ-i-kul ud-VAN-sments", bn: "প্রযুক্তিগত অগ্রগতি" },
        { w: "Advent", ipa: "AD-vent", bn: "আগমন / আবির্ভাব" },
        { w: "Fundamentally transformed", ipa: "fun-duh-MEN-tuh-lee trans-FORMD", bn: "মৌলিকভাবে রূপান্তরিত করেছে" },
        { w: "Interaction", ipa: "in-tur-AK-shun", bn: "মিথস্ক্রিয়া / পারস্পরিক যোগাযোগ" },
        { w: "Relationship dynamics", ipa: "ri-LAY-shun-ship dye-NAM-iks", bn: "সম্পর্কের গতিশীলতা বা ধরন" },
        { w: "Drawbacks", ipa: "DRAW-baks", bn: "অসুবিধা / নেতিবাচক দিক" },
        { w: "Geographical barriers", ipa: "jee-uh-GRAF-i-kul BAR-ee-urz", bn: "ভৌগোলিক বাধা" },
        { w: "Confined", ipa: "kun-FYNED", bn: "সীমাবদ্ধ / গণ্ডিবদ্ধ" },
        { w: "Maintain close ties", ipa: "mayn-TAYN klohss tyze", bn: "ঘনিষ্ঠ সম্পর্ক বজায় রাখা" },
        { w: "Forge new connections", ipa: "forj nyoo kuh-NEK-shunz", bn: "নতুন সম্পর্ক বা সংযোগ তৈরি করা" },
        { w: "Instant messaging", ipa: "IN-stunt MES-i-jing", bn: "তাৎক্ষণিক বার্তা আদান-প্রদান" },
        { w: "Superficial", ipa: "soo-pur-FISH-ul", bn: "অগভীর / ভাসা-ভাসা" },
        { w: "Predominantly", ipa: "pri-DOM-i-nunt-lee", bn: "প্রধানত / মূলত" },
        { w: "Democratization of connection", ipa: "di-mok-ruh-ty-ZAY-shun uv kuh-NEK-shun", bn: "যোগাযোগের সর্বজনীনকরণ বা গণতান্ত্রিকীকরণ" },
        { w: "Erode", ipa: "i-ROHD", bn: "ক্ষয় করা / ধীরে ধীরে নষ্ট করা" },
        { w: "Unrealistic expectations", ipa: "un-ree-uh-LIS-tik ek-spek-TAY-shunz", bn: "অবাস্তব প্রত্যাশা" },
        { w: "Revolutionized", ipa: "rev-uh-LOO-shuh-nyzed", bn: "বৈপ্লবিক পরিবর্তন এনেছে" },
        { w: "Instantaneous", ipa: "in-stun-TAY-nee-us", bn: "তাৎক্ষণিক / মুহূর্তের মধ্যে ঘটে এমন" },
        { w: "Undeniable", ipa: "un-di-NYE-uh-bul", bn: "অনস্বীকার্য" },
        { w: "Unprecedented", ipa: "un-PRES-i-den-tid", bn: "অভূতপূর্ব / নজিরবিহীন" },
        { w: "Rising prevalence", ipa: "RYE-zing PREV-uh-lunss", bn: "ক্রমবর্ধমান প্রাদুর্ভাব বা ব্যাপকতা" },
        { w: "Diet-related health issues", ipa: "DYE-ut ri-LAY-tid helth ISH-ooz", bn: "খাদ্যাভ্যাসজনিত স্বাস্থ্য সমস্যা" },
        { w: "Overconsumption", ipa: "oh-vur-kun-SUMP-shun", bn: "অতিরিক্ত গ্রহণ বা অতিরিক্ত খাওয়া" },
        { w: "Deterrent", ipa: "di-TER-unt", bn: "নিবৃত্তকারী / প্রতিরোধক" },
        { w: "Economic disincentive", ipa: "ee-kuh-NOM-ik dis-in-SEN-tiv", bn: "অর্থনৈতিক নিরুৎসাহক ব্যবস্থা" },
        { w: "Subsidize", ipa: "SUB-si-dyze", bn: "ভর্তুকি দেওয়া / আংশিক খরচ বহন করা" },
        { w: "Alleviate the strain", ipa: "uh-LEE-vee-ayt thuh strayn", bn: "চাপ লাঘব করা বা কমানো" }
    ],
    // Page 4: Crime, Law, Zoos & Workplace
    [
        { w: "Penal system", ipa: "PEE-nul SIS-tum", bn: "দণ্ডবিধি ব্যবস্থা / অপরাধ ও শাস্তি বিষয়ক ব্যবস্থা" },
        { w: "Deeply polarizing", ipa: "DEEP-lee POH-luh-rye-zing", bn: "গভীরভাবে মতভেদ সৃষ্টিকারী" },
        { w: "Rehabilitation", ipa: "ree-huh-bil-i-TAY-shun", bn: "পুনর্বাসন / স্বাভাবিক জীবনে ফিরিয়ে আনা" },
        { w: "Inmates", ipa: "IN-mayts", bn: "কারাবন্দি / কয়েদি" },
        { w: "Humane approach", ipa: "hyoo-MAYN uh-PROHCH", bn: "মানবিক দৃষ্টিভঙ্গি বা পদ্ধতি" },
        { w: "Deterrence", ipa: "di-TER-unss", bn: "প্রতিরোধ / ভীতি প্রদর্শনের মাধ্যমে নিবৃত্ত করা" },
        { w: "Deprivation of liberty", ipa: "dep-ri-VAY-shun uv LIB-ur-tee", bn: "স্বাধীনতা হরণ" },
        { w: "Retribution", ipa: "ret-ri-BYOO-shun", bn: "চরম শাস্তি / প্রতিশোধমূলক বিচার" },
        { w: "Lenient", ipa: "LEE-nee-unt", bn: "নমনীয় / শিথিল / কোমল" },
        { w: "Incarceration", ipa: "in-kar-suh-RAY-shun", bn: "কারাবাস / বন্দিদশা" },
        { w: "Vocational training", ipa: "voh-KAY-shuh-nul TRAY-ning", bn: "বৃত্তিমূলক বা পেশাভিত্তিক প্রশিক্ষণ" },
        { w: "Reintegrate", ipa: "ree-IN-ti-grayt", bn: "পুনরায় সমাজে অন্তর্ভুক্ত করা" },
        { w: "Marginalized", ipa: "MAR-juh-nuh-lyzed", bn: "প্রান্তিক / সমাজ থেকে বিচ্ছিন্ন বা অবহেলিত" },
        { w: "Recidivism rates", ipa: "ri-SID-i-viz-um rayts", bn: "পুনরায় অপরাধ করার প্রবণতার হার" },
        { w: "Captivity", ipa: "kap-TIV-i-tee", bn: "বন্দিদশা / খাঁচায় বা ঘেরাও করে রাখা অবস্থা" },
        { w: "Inherently cruel", ipa: "in-HEER-unt-lee KROO-ul", bn: "স্বভাবতই বা জন্মগতভাবেই নিষ্ঠুর" },
        { w: "Wildlife conservation", ipa: "WYLD-lyfe kon-sur-VAY-shun", bn: "বন্যপ্রাণী সংরক্ষণ" },
        { w: "Endangered species", ipa: "in-DAYN-jurd SPEE-sheez", bn: "বিপন্ন বা বিলুপ্তপ্রায় প্রজাতি" },
        { w: "Zoochosis", ipa: "zoo-KOH-sis", bn: "চিড়িয়াখানায় প্রাণীদের মানসিক রোগ" },
        { w: "Sentient beings", ipa: "SEN-shunt BEE-ingz", bn: "অনুভূতিশীল প্রাণী" },
        { w: "Indispensable role", ipa: "in-di-SPEN-suh-bul rohl", bn: "অপরিহার্য ভূমিকা" },
        { w: "Deforestation", ipa: "dee-for-i-STAY-shun", bn: "বন উজাড়" },
        { w: "Captive breeding", ipa: "KAP-tiv BREE-ding", bn: "বন্দি অবস্থায় প্রজনন করানো" },
        { w: "Brink of extinction", ipa: "bringk uv ik-STINGK-shun", bn: "বিলুপ্তির দ্বারপ্রান্তে" },
        { w: "Telecommuting", ipa: "TEL-i-kuh-myoo-ting", bn: "ঘরে বসে অনলাইনে অফিস করা" },
        { w: "Viable reality", ipa: "VYE-uh-bul ree-AL-i-tee", bn: "বাস্তবসম্মত বা কার্যকর বাস্তবতা" },
        { w: "Work-life balance", ipa: "wurk lyfe BAL-unss", bn: "কর্মজীবন ও ব্যক্তিগত জীবনের ভারসাম্য" }
    ],
    // Page 5: Language Extinction, Animal Testing & Heritage
    [
        { w: "Extinction", ipa: "ik-STINGK-shun", bn: "বিলুপ্তি / সম্পূর্ণ ধ্বংস" },
        { w: "Phenomenon", ipa: "fi-NOM-uh-non", bn: "ঘটনা / বিষয়" },
        { w: "Irreplaceable", ipa: "ir-i-PLAY-suh-bul", bn: "অপূরণীয় / যার কোনো বিকল্প নেই" },
        { w: "Utilitarian view", ipa: "yoo-til-i-TAIR-ee-un vyoo", bn: "উপযোগবাদী দৃষ্টিভঙ্গি / বাস্তবমুখী চিন্তাধারা" },
        { w: "Linguistic diversity", ipa: "ling-GWIS-tik dye-VUR-si-tee", bn: "ভাষাগত বৈচিত্র্য" },
        { w: "Cognitive processes", ipa: "KOG-ni-tiv PROH-ses-iz", bn: "জ্ঞানীয় বা চিন্তন প্রক্রিয়া" },
        { w: "Ethical dilemma", ipa: "ETH-i-kul di-LEM-uh", bn: "নৈতিক দ্বিধা বা সংকট" },
        { w: "Unavoidable necessity", ipa: "un-uh-VOY-duh-bul ni-SES-i-tee", bn: "অনিবার্য প্রয়োজনীয়তা" },
        { w: "Physiological", ipa: "fiz-ee-uh-LOJ-i-kul", bn: "শারীরবৃত্তীয়" },
        { w: "Primates", ipa: "PRYE-mayts", bn: "প্রাইমেট (বানর/শিম্পাঞ্জি জাতীয় প্রাণী)" },
        { w: "Sentient beings", ipa: "SEN-shunt BEE-ingz", bn: "অনুভূতিশীল প্রাণী" },
        { w: "Epidemiological studies", ipa: "ep-i-dee-mee-uh-LOJ-i-kul STUD-eez", bn: "মহামারী বা রোগ বিস্তার সংক্রান্ত গবেষণা" },
        { w: "Dilapidated", ipa: "di-LAP-i-day-tid", bn: "জরাজীর্ণ / ভগ্নপ্রায়" },
        { w: "Tangible link", ipa: "TAN-juh-bul lingk", bn: "বাস্তব যোগসূত্র" },
        { w: "Adaptive reuse", ipa: "uh-DAP-tiv ree-YOOSS", bn: "অভিযোজিত পুনর্ব্যবহার" },
        { w: "Facades", ipa: "fuh-SAHDZ", bn: "ভবনের সম্মুখভাগ" },
        { w: "Heritage", ipa: "HER-i-tij", bn: "ঐতিহ্য" }
    ],
    // Page 6: Aging Society, Water Scarcity & Privacy
    [
        { w: "Demographic shift", ipa: "dem-uh-GRAF-ik shift", bn: "জনসংখ্যাগত পরিবর্তন" },
        { w: "Outnumber", ipa: "owt-NUM-bur", bn: "সংখ্যায় ছাড়িয়ে যাওয়া" },
        { w: "Retirees / Pensioners", ipa: "ri-tye-REEZ / PEN-shuh-nurz", bn: "অবসরপ্রাপ্ত ব্যক্তি / পেনশনার" },
        { w: "Stagnation", ipa: "stag-NAY-shun", bn: "স্থবিরতা / আটকে থাকা অবস্থা" },
        { w: "Water scarcity", ipa: "WAW-tur SKAIR-si-tee", bn: "পানির ঘাটতি বা দুষ্প্রাপ্যতা" },
        { w: "Arid regions", ipa: "AR-id REE-junz", bn: "শুষ্ক বা খরাপ্রবণ অঞ্চল" },
        { w: "Burgeoning demand", ipa: "BUR-juh-ning di-MAND", bn: "দ্রুত বর্ধনশীল চাহিদা" },
        { w: "Desalination plants", ipa: "dee-sal-i-NAY-shun plants", bn: "লবণাক্ততা দূরীকরণ কেন্দ্র" },
        { w: "Digital footprints", ipa: "DIJ-i-tul FOOT-prints", bn: "ডিজিটাল পদচিহ্ন" },
        { w: "Monetized", ipa: "MON-i-tyzed", bn: "বাণিজ্যিকভাবে কাজে লাগানো" },
        { w: "Intrusive", ipa: "in-TROO-siv", bn: "অনধিকারপ্রবেশকারী / ব্যক্তিগত পরিসরে হস্তক্ষেপকারী" },
        { w: "Vulnerabilities", ipa: "vul-nur-uh-BIL-i-teez", bn: "দুর্বলতা / সহজে আক্রান্ত হওয়ার অবস্থা" },
        { w: "Identity theft", ipa: "eye-DEN-ti-tee theft", bn: "পরিচয় চুরি" },
        { w: "Anonymity", ipa: "an-uh-NIM-i-tee", bn: "বেনামি অবস্থা / পরিচয়ের গোপনীয়তা" }
    ],
    // Page 7: Gender Pay Gap, Migration & Rubbish
    [
        { w: "Entrenched", ipa: "in-TRENCHT", bn: "বদ্ধমূল / গভীরভাবে প্রোথিত" },
        { w: "Unconscious bias", ipa: "un-KON-shus BYE-us", bn: "অবচেতন বা অজান্তেই হওয়া পক্ষপাতিত্ব" },
        { w: "Glass ceiling", ipa: "glahss SEE-ling", bn: "অদৃশ্য বাধা (নারীদের শীর্ষ পদে যাওয়ার পথে)" },
        { w: "Motherhood penalty", ipa: "MUDH-ur-hood PEN-ul-tee", bn: "মাতৃত্বকালীন ক্যারিয়ার ক্ষতি" },
        { w: "Paternity leave", ipa: "puh-TUR-ni-tee leev", bn: "পিতৃত্বকালীন ছুটি" },
        { w: "Proliferation", ipa: "pruh-lif-uh-RAY-shun", bn: "দ্রুত বিস্তার / সংখ্যাবৃদ্ধি" },
        { w: "Sprawling", ipa: "SPRAW-ling", bn: "এলোমেলোভাবে ছড়িয়ে পড়া" },
        { w: "Unsanitary", ipa: "un-SAN-i-tair-ee", bn: "অস্বাস্থ্যকর / নোংরা" },
        { w: "Brain drain", ipa: "brayn drayn", bn: "মেধা পাচার" },
        { w: "Decentralizing", ipa: "dee-SEN-truh-lye-zing", bn: "বিকেন্দ্রীকরণ" },
        { w: "Planned obsolescence", ipa: "pland ob-suh-LES-unss", bn: "পরিকল্পিত অপ্রচলিতকরণ" },
        { w: "Non-biodegradable", ipa: "non bye-oh-di-GRAY-duh-bul", bn: "অপচনশীল" },
        { w: "Right to repair", ipa: "ryte too ri-PAIR", bn: "মেরামতের অধিকার" },
        { w: "Composting", ipa: "KOM-post-ing", bn: "জৈব সার তৈরি করা" }
    ],
    // Page 8: Fossil Fuels, Testing & Endangered Animals
    [
        { w: "Combustion", ipa: "kum-BUS-chun", bn: "দহন / পোড়ানো" },
        { w: "Volatile", ipa: "VOL-uh-tyle", bn: "অস্থিতিশীল / পরিবর্তনশীল" },
        { w: "Inexhaustible", ipa: "in-ig-ZAW-stuh-bul", bn: "অফুরন্ত / যা কখনো শেষ হয় না" },
        { w: "Existential threat", ipa: "eg-zi-STEN-shul thret", bn: "অস্তিত্বের সংকট বা চরম হুমকি" },
        { w: "Cornerstone", ipa: "KOR-nur-stohn", bn: "ভিত্তিপ্রস্তর / মূল ভিত্তি" },
        { w: "Invigilation", ipa: "in-vij-i-LAY-shun", bn: "পরীক্ষা কক্ষের নজরদারি" },
        { w: "Plagiarism", ipa: "PLAY-juh-riz-um", bn: "কুম্ভিলকবৃত্তি / অন্যের লেখা চুরি করা" },
        { w: "Rote memorization", ipa: "roht mem-uh-ry-ZAY-shun", bn: "না বুঝে মুখস্থ করা" },
        { w: "Imperative", ipa: "im-PER-uh-tiv", bn: "অত্যাবশ্যক / বাধ্যতামূলক" },
        { w: "Precedence", ipa: "PRES-i-dunss", bn: "অগ্রাধিকার" },
        { w: "Domino effect", ipa: "DOM-i-noh i-FEKT", bn: "ডমিনো ইফেক্ট (একটির প্রভাবে অন্যটি ঘটা)" },
        { w: "False dichotomy", ipa: "fawlss dye-KOT-uh-mee", bn: "মিথ্যা দ্বিধাবিভক্তি" },
        { w: "Self-preservation", ipa: "self prez-ur-VAY-shun", bn: "আত্মরক্ষা / নিজেকে টিকিয়ে রাখা" }
    ]
];

// =========================================================================
// PDF 2: IELTS Listening 1200 High-Frequency Words (Complete)
// =========================================================================
const pdf2Data = [
    // Page 1: Days, Months, Money Matters & Subjects
    [
        { w: "Monday", ipa: "Mun-day", bn: "সোমবার" },
        { w: "Tuesday", ipa: "Tooz-day", bn: "মঙ্গলবার" },
        { w: "Wednesday", ipa: "Wenz-day", bn: "বুধবার" },
        { w: "Thursday", ipa: "Thurz-day", bn: "বৃহস্পতিবার" },
        { w: "Friday", ipa: "Fry-day", bn: "শুক্রবার" },
        { w: "Saturday", ipa: "Sat-er-day", bn: "শনিবার" },
        { w: "Sunday", ipa: "Sun-day", bn: "রবিবার" },
        { w: "Weekdays", ipa: "Week-dayz", bn: "কর্মদিবস" },
        { w: "Weekend", ipa: "Week-end", bn: "সপ্তাহান্ত" },
        { w: "January", ipa: "Jan-yoo-er-ee", bn: "জানুয়ারী" },
        { w: "February", ipa: "Feb-roo-er-ee", bn: "ফেব্রুয়ারী" },
        { w: "March", ipa: "March", bn: "মার্চ" },
        { w: "April", ipa: "Ay-pril", bn: "এপ্রিল" },
        { w: "May", ipa: "May", bn: "মে" },
        { w: "June", ipa: "Joon", bn: "জুন" },
        { w: "July", ipa: "Joo-ly", bn: "জুলাই" },
        { w: "August", ipa: "Aw-gust", bn: "আগস্ট" },
        { w: "September", ipa: "Sep-tem-ber", bn: "সেপ্টেম্বর" },
        { w: "October", ipa: "Ok-toh-ber", bn: "অক্টোবর" },
        { w: "November", ipa: "No-vem-ber", bn: "নভেম্বর" },
        { w: "December", ipa: "Di-sem-ber", bn: "ডিসেম্বর" },
        { w: "Cash", ipa: "Kash", bn: "নগদ" },
        { w: "Debit", ipa: "Deb-it", bn: "ডেবিট" },
        { w: "Credit card", ipa: "Kred-it kard", bn: "ক্রেডিট কার্ড" },
        { w: "Cheque", ipa: "Chek", bn: "চেক" },
        { w: "In advance", ipa: "In ad-vans", bn: "অগ্রিম" },
        { w: "Annual fee", ipa: "An-yoo-ul fee", bn: "বার্ষিক ফি" },
        { w: "Monthly membership", ipa: "Munth-lee mem-ber-ship", bn: "মাসিক সদস্যতা" },
        { w: "Interest rate", ipa: "In-ter-est rayt", bn: "সুদের হার" },
        { w: "Deposit", ipa: "Di-poz-it", bn: "আমানত" },
        { w: "Tuition fees", ipa: "Too-ish-un fee", bn: "টিউশন ফি" },
        { w: "Poverty", ipa: "Pov-er-tee", bn: "দারিদ্র্য" },
        { w: "Bank statement", ipa: "Bank stayt-ment", bn: "ব্যাংক স্টেটমেন্ট" },
        { w: "Money management", ipa: "Mun-ee man-ij-ment", bn: "অর্থ ব্যবস্থাপনা" },
        { w: "Current account", ipa: "Kur-ent uh-kount", bn: "চলতি হিসাব" },
        { w: "Student account", ipa: "Stoo-dent uh-kount", bn: "ছাত্র হিসাব" },
        { w: "Withdraw", ipa: "With-draw", bn: "উত্তোলন" },
        { w: "Low-risk investment", ipa: "Loh-risk in-vest-ment", bn: "কম ঝুঁকির বিনিয়োগ" },
        { w: "Mortgage", ipa: "Mor-gij", bn: "বন্ধক" },
        { w: "Grace period", ipa: "Grays peer-ee-ud", bn: "গ্রেস পিরিয়ড" },
        { w: "Budget deficit", ipa: "Buj-it def-uh-sit", bn: "বাজেট ঘাটতি" },
        { w: "Retail voucher", ipa: "Ree-tayl vow-cher", bn: "খুচরা ভাউচার" },
        { w: "Coupon", ipa: "Koo-pon", bn: "কুপন" },
        { w: "Counterfeit money", ipa: "Koun-ter-fit mun-ee", bn: "জাল টাকা" },
        { w: "Public money", ipa: "Pub-lik mun-ee", bn: "সরকারি অর্থ" },
        { w: "Tax payers' money", ipa: "Taks pay-erz mun-ee", bn: "করদাতাদের অর্থ" },
        { w: "Debt", ipa: "Det", bn: "ঋণ" },
        { w: "Interest-free credit", ipa: "In-ter-est-free kred-it", bn: "সুদমুক্ত ক্রেডিট" },
        { w: "Purchase", ipa: "Pur-chus", bn: "ক্রয়" },
        { w: "Partial refund", ipa: "Par-shul ree-fund", bn: "আংশিক ফেরত" },
        { w: "Annuity", ipa: "Uh-noo-i-tee", bn: "বার্ষিক ভাতা" },
        { w: "Non-refundable", ipa: "Non-ree-fun-duh-bul", bn: "অফেরতযোগ্য" },
        { w: "Master card", ipa: "Mas-ter kard", bn: "মাস্টার কার্ড" },
        { w: "Visa", ipa: "Vee-zuh", bn: "ভিসা" },
        { w: "Distribution costs", ipa: "Dis-tri-byoo-shun kosts", bn: "বিতরণ ব্যয়" },
        { w: "Income", ipa: "In-kum", bn: "আয়" },
        { w: "Finance department", ipa: "Fy-nans di-part-ment", bn: "অর্থ বিভাগ" },
        { w: "Family finances", ipa: "Fam-lee fy-nans-es", bn: "পারিবারিক অর্থ" },
        { w: "Duty-free store", ipa: "Doo-tee free stor", bn: "ডিউটি ফ্রি দোকান" }
    ],
    // Page 2: College, University, Marketing & Health
    [
        { w: "Science", ipa: "Sy-ens", bn: "বিজ্ঞান" },
        { w: "Politics", ipa: "Pol-i-tiks", bn: "রাজনীতি" },
        { w: "History", ipa: "His-tuh-ree", bn: "ইতিহাস" },
        { w: "Biology", ipa: "By-ol-uh-jee", bn: "জীববিজ্ঞান" },
        { w: "Architecture", ipa: "Ar-ki-tek-cher", bn: "স্থাপত্য" },
        { w: "Law", ipa: "Law", bn: "আইন" },
        { w: "Geography", ipa: "Jee-og-ruh-fee", bn: "ভূগোল" },
        { w: "Archaeology", ipa: "Ar-kee-ol-uh-jee", bn: "পুরাতত্ত্ব" },
        { w: "Literature", ipa: "Lit-er-uh-cher", bn: "সাহিত্য" },
        { w: "Business management", ipa: "Biz-nis man-ij-ment", bn: "ব্যবসায় ব্যবস্থাপনা" },
        { w: "Agriculture", ipa: "Ag-ri-kul-cher", bn: "কৃষি" },
        { w: "Statistics", ipa: "Stuh-tis-tiks", bn: "পরিসংখ্যান" },
        { w: "Mathematics", ipa: "Math-uh-mat-iks", bn: "গণিত" },
        { w: "Logic", ipa: "Loj-ik", bn: "যুক্তিবিদ্যা" },
        { w: "Physics", ipa: "Fiz-iks", bn: "পদার্থবিদ্যা" },
        { w: "Psychology", ipa: "Sy-kol-uh-jee", bn: "মনোবিজ্ঞান" },
        { w: "Anthropology", ipa: "An-thruh-pol-uh-jee", bn: "নৃবিজ্ঞান" },
        { w: "Economics", ipa: "Ee-kuh-nom-iks", bn: "অর্থনীতি" },
        { w: "Philosophy", ipa: "Fi-los-uh-fee", bn: "দর্শন" },
        { w: "Performing arts", ipa: "Per-form-ing arts", bn: "পরিবেশন শিল্প" },
        { w: "Visual arts", ipa: "Vizh-oo-ul arts", bn: "দৃশ্য শিল্প" },
        { w: "Chemistry", ipa: "Kem-uh-stree", bn: "রসায়ন" },
        { w: "Humanities", ipa: "Hyoo-man-i-teez", bn: "মানবিক" },
        { w: "Course outline", ipa: "Kors owt-lyne", bn: "কোর্স আউটলাইন" },
        { w: "Group discussion", ipa: "Groop dis-kuh-shun", bn: "গ্রুপ আলোচনা" },
        { w: "Handout", ipa: "Hand-owt", bn: "হ্যান্ডআউট" },
        { w: "Written work", ipa: "Rit-n wurk", bn: "লিখিত কাজ" },
        { w: "Report writing", ipa: "Ri-port ry-ting", bn: "প্রতিবেদন লেখা" },
        { w: "Research", ipa: "Ree-surch", bn: "গবেষণা" },
        { w: "Proofreading", ipa: "Proof-ree-ding", bn: "প্রুফরিডিং" },
        { w: "Experiment", ipa: "Ik-sper-uh-ment", bn: "পরীক্ষা" },
        { w: "Experience", ipa: "Ik-speer-ee-uns", bn: "অভিজ্ঞতা" },
        { w: "Reference", ipa: "Ref-rens", bn: "রেফারেন্স" },
        { w: "Textbook", ipa: "Teks-book", bn: "পাঠ্যপুস্তক" },
        { w: "Dictionary", ipa: "Dik-shuh-ner-ee", bn: "অভিধান" },
        { w: "Laptop", ipa: "Lap-top", bn: "ল্যাপটপ" },
        { w: "Printer", ipa: "Prin-ter", bn: "প্রিন্টার" },
        { w: "Student advisor", ipa: "Stoo-dent ad-vy-zer", bn: "ছাত্র উপদেষ্টা" },
        { w: "Teamwork", ipa: "Teem-wurk", bn: "দলগত কাজ" },
        { w: "Module", ipa: "Moj-ool", bn: "মডিউল" },
        { w: "Topic", ipa: "Top-ik", bn: "বিষয়" },
        { w: "Assessment", ipa: "Uh-ses-ment", bn: "মূল্যায়ন" },
        { w: "Library", ipa: "Ly-brer-ee", bn: "গ্রন্থাগার" },
        { w: "Department", ipa: "Di-part-ment", bn: "বিভাগ" },
        { w: "Computer center", ipa: "Kum-pyoo-ter sen-ter", bn: "কম্পিউটার কেন্দ্র" },
        { w: "Classroom", ipa: "Klas-room", bn: "শ্রেণিকক্ষ" },
        { w: "Lecture", ipa: "Lek-cher", bn: "বক্তৃতা" },
        { w: "Tutor", ipa: "Too-ter", bn: "টিউটর" },
        { w: "Main hall", ipa: "Mayn hawl", bn: "প্রধান হল" },
        { w: "Attendance", ipa: "Uh-ten-duns", bn: "উপস্থিতি" },
        { w: "Deadline", ipa: "Ded-lyne", bn: "শেষ তারিখ" },
        { w: "Computer laboratory", ipa: "Kum-pyoo-ter lab-ruh-tor-ee", bn: "কম্পিউটার ল্যাব" },
        { w: "Certificate", ipa: "Ser-tif-uh-kit", bn: "সার্টিফিকেট" },
        { w: "Diploma", ipa: "Di-ploh-muh", bn: "ডিপ্লোমা" },
        { w: "Placement test", ipa: "Plays-ment test", bn: "প্লেসমেন্ট টেস্ট" },
        { w: "Overseas students", ipa: "Oh-ver-seez stoo-dents", bn: "বিদেশী ছাত্র" },
        { w: "Full-time", ipa: "Fool tym", bn: "পূর্ণকালীন" },
        { w: "Facilities", ipa: "Fuh-sil-uh-teez", bn: "সুবিধা" },
        { w: "College", ipa: "Kol-ij", bn: "কলেজ" },
        { w: "Specialist", ipa: "Spesh-uh-list", bn: "বিশেষজ্ঞ" },
        { w: "Accommodation", ipa: "Uh-kom-uh-day-shun", bn: "থাকার ব্যবস্থা" },
        { w: "Dissertation", ipa: "Dis-er-tay-shun", bn: "গবেষণাপত্র" },
        { w: "Questionnaire", ipa: "Kwes-chuh-nair", bn: "প্রশ্নপত্র" },
        { w: "Catalog", ipa: "Kat-uh-log", bn: "ক্যাটালগ" },
        { w: "Interview", ipa: "In-ter-vyoo", bn: "সাক্ষাৎকার" },
        { w: "Newsletter", ipa: "Nooz-let-er", bn: "নিউজলেটার" },
        { w: "Competition", ipa: "Kom-puh-tish-un", bn: "প্রতিযোগিতা" },
        { w: "Profit margin", ipa: "Prof-it mar-jin", bn: "লাভের হার" },
        { w: "Balanced diet", ipa: "Bal-unst dy-ut", bn: "সুষম খাদ্য" },
        { w: "Food pyramid", ipa: "Food pir-uh-mid", bn: "খাদ্য পিরামিড" },
        { w: "Carbohydrates", ipa: "Kar-boh-hy-drayts", bn: "শর্করা" }
    ],
    // Page 3: Nature, Environment, Animals, Places & Homes
    [
        { w: "Waterfall", ipa: "Waw-ter-fawl", bn: "জলপ্রপাত" },
        { w: "Environment", ipa: "En-vy-run-ment", bn: "পরিবেশ" },
        { w: "Mountain", ipa: "Moun-tn", bn: "পর্বত" },
        { w: "Peninsula", ipa: "Puh-nin-suh-luh", bn: "উপদ্বীপ" },
        { w: "Earthquake", ipa: "Urth-kwayk", bn: "ভূমিকম্প" },
        { w: "Avalanche", ipa: "Av-uh-lanch", bn: "হিমপাত" },
        { w: "Tornado", ipa: "Tor-nay-doh", bn: "টর্নেডো" },
        { w: "Desertification", ipa: "Di-zur-tuh-fi-kay-shun", bn: "মরুকরণ" },
        { w: "Volcano", ipa: "Vol-kay-noh", bn: "আগ্নেয়গিরি" },
        { w: "Disaster", ipa: "Di-zas-ter", bn: "বিপর্যয়" },
        { w: "Catastrophe", ipa: "Kuh-tas-truh-fee", bn: "মহাবিপর্যয়" },
        { w: "Erosion", ipa: "Ih-roh-zhun", bn: "ক্ষয়" },
        { w: "Landslides", ipa: "Land-slydz", bn: "ভূমিধস" },
        { w: "Greenhouse effect", ipa: "Green-hows uh-fekt", bn: "গ্রিনহাউস প্রভাব" },
        { w: "Acid rain", ipa: "As-id rayn", bn: "অ্যাসিড বৃষ্টি" },
        { w: "Global warming", ipa: "Gloh-bul wor-ming", bn: "বৈশ্বিক উষ্ণায়ন" },
        { w: "Carbon dioxide", ipa: "Kar-bun dy-ok-syd", bn: "কার্বন ডাইঅক্সাইড" },
        { w: "Exhaust fumes", ipa: "Eg-zost fyoomz", bn: "নিষ্কাশন ধোঁয়া" },
        { w: "Deforestation", ipa: "Dee-for-uh-stay-shun", bn: "বন উজাড়" },
        { w: "Smog", ipa: "Smog", bn: "ধোঁয়াশা" },
        { w: "Pollution", ipa: "Puh-loo-shun", bn: "দূষণ" },
        { w: "Wind turbine", ipa: "Wind tur-byn", bn: "বায়ু টারবাইন" },
        { w: "Solar panels", ipa: "Soh-ler pan-ulz", bn: "সৌর প্যানেল" },
        { w: "Renewable", ipa: "Ri-noo-uh-bul", bn: "নবায়নযোগ্য" },
        { w: "Environmentally friendly", ipa: "En-vy-run-men-tuh-lee frend-lee", bn: "পরিবেশ বান্ধব" },
        { w: "Contaminated", ipa: "Kun-tam-uh-nay-tid", bn: "দূষিত" },
        { w: "Drought", ipa: "Drout", bn: "খরা" },
        { w: "Fossil fuels", ipa: "Fos-ul fyoo-ulz", bn: "জীবাশ্ম জ্বালানি" },
        { w: "Mammals", ipa: "Mam-ulz", bn: "স্তন্যপায়ী" },
        { w: "Cetacean", ipa: "Si-tay-shun", bn: "তিমি জাতীয় প্রাণী" },
        { w: "Amphibian", ipa: "Am-fib-ee-un", bn: "উভচর" },
        { w: "Reptile", ipa: "Rep-tyl", bn: "সরীসৃপ" },
        { w: "Fertilizer", ipa: "Fur-tuh-ly-zer", bn: "সার" },
        { w: "Antarctica", ipa: "Ant-ark-ti-kuh", bn: "অ্যান্টার্কটিকা" },
        { w: "Linguistics", ipa: "Ling-gwis-tiks", bn: "ভাষাবিজ্ঞান" },
        { w: "Bilingual", ipa: "By-ling-gwul", bn: "দ্বিভাষিক" },
        { w: "Polyglot", ipa: "Pol-ee-glot", bn: "বহুভাষিক" },
        { w: "Skyscraper", ipa: "Sky-skray-per", bn: "আকাশচুম্বী ভবন" },
        { w: "Semi-detached house", ipa: "Sem-ee-di-tacht hows", bn: "আধা-সংযুক্ত বাড়ি" },
        { w: "Condominium", ipa: "Kon-duh-min-ee-um", bn: "কন্ডোমিনিয়াম" },
        { w: "Department store", ipa: "Di-part-ment stor", bn: "ডিপার্টমেন্ট স্টোর" },
        { w: "Technical cooperation", ipa: "Tek-ni-kul ko-op-uh-ray-shun", bn: "প্রযুক্তিগত সহযোগিতা" }
    ],
    // Page 4: Sports, Transport, Equipment & Other Terms
    [
        { w: "Extreme sports", ipa: "Ik-streem sports", bn: "এক্সট্রিম স্পোর্টস" },
        { w: "Paragliding", ipa: "Par-uh-gly-ding", bn: "প্যারাগ্লাইডিং" },
        { w: "Skydiving", ipa: "Sky-dy-ving", bn: "স্কাইডাইভিং" },
        { w: "Bungee jumping", ipa: "Bun-gee jump-ing", bn: "বাঞ্জি জাম্পিং" },
        { w: "White-water rafting", ipa: "Wyt-waw-ter raf-ting", bn: "সাদা জল রাফটিং" },
        { w: "Cylindrical", ipa: "Si-lin-dri-kuhl", bn: "নলাকার" },
        { w: "Measurements", ipa: "Mezh-er-ments", bn: "পরিমাপ" },
        { w: "Altitude", ipa: "AL-ti-tood", bn: "উচ্চতা" },
        { w: "Imperial system", ipa: "im-PEER-ee-ul SIS-tem", bn: "ইম্পেরিয়াল পদ্ধতি" },
        { w: "Metric system", ipa: "MET-rik SIS-tem", bn: "মেট্রিক পদ্ধতি" },
        { w: "Hovercraft", ipa: "Huv-er-kraft", bn: "হোভারক্রাফট" },
        { w: "Hydrofoil", ipa: "Hy-droh-foyl", bn: "হাইড্রোফয়েল" },
        { w: "Hot-air balloon", ipa: "Hot-air buh-loon", bn: "হট-এয়ার বেলুন" },
        { w: "Weather forecast", ipa: "Weth-er for-kast", bn: "আবহাওয়ার পূর্বাভাস" },
        { w: "Musical instrument", ipa: "Myoo-zi-kul in-struh-ment", bn: "বাদ্যযন্ত্র" },
        { w: "Mechanical pencil", ipa: "Mi-kan-i-kul pen-suhl", bn: "মেকানিক্যাল পেন্সিল" },
        { w: "Classical music", ipa: "Klas-i-kuhl myoo-zik", bn: "শাস্ত্রীয় সঙ্গীত" },
        { w: "Curriculum vitae", ipa: "Kuh-rik-yuh-luhm vee-tay", bn: "জীবনবৃত্তান্ত" },
        { w: "Flight attendant", ipa: "Flyt uh-ten-duhnt", bn: "ফ্লাইট অ্যাটেন্ডেন্ট" },
        { w: "Millennium", ipa: "Mi-len-ee-um", bn: "সহস্রাব্দ" },
        { w: "Fortnight", ipa: "Fort-nyt", bn: "পাক্ষিক" },
        { w: "Indigenous", ipa: "In-dij-uh-nus", bn: "আদিবাসী" },
        { w: "Pedestrian safety", ipa: "Pe-des-tree-uhn sayf-tee", bn: "পথচারী নিরাপত্তা" },
        { w: "Liberal democracy", ipa: "Lib-er-ul di-mok-ruh-see", bn: "উদারনৈতিক গণতন্ত্র" },
        { w: "Nature conservation", ipa: "Nay-cher kon-ser-vay-shun", bn: "প্রকৃতি সংরক্ষণ" },
        { w: "Life expectancy", ipa: "Lyf ik-spek-tun-see", bn: "আয়ু প্রত্যাশা" },
        { w: "Encyclopedia", ipa: "En-sy-kluh-pee-dee-uh", bn: "বিশ্বকোষ" },
        { w: "Evolution", ipa: "Ev-uh-loo-shun", bn: "বিবর্তন" },
        { w: "Revolution", ipa: "Rev-uh-loo-shun", bn: "বিপ্লব" },
        { w: "Illiteracy", ipa: "Il-lit-er-uh-see", bn: "নিরক্ষরতা" },
        { w: "Proficiency", ipa: "Pruh-fish-un-see", bn: "দক্ষতা" },
        { w: "Sufficient", ipa: "Suh-fish-unt", bn: "পর্যাপ্ত" }
    ],
    // Page 5: Animals, Insects, Marine Life & Plants
    [
        { w: "Birds of prey", ipa: "Burdz uv pray", bn: "শিকারী পাখি" },
        { w: "Seabirds", ipa: "See-burdz", bn: "সামুদ্রিক পাখি" },
        { w: "Poultry and game", ipa: "Pohl-tree and gaym", bn: "পোল্ট্রি ও শিকার" },
        { w: "Whale", ipa: "Wayl", bn: "তিমি" },
        { w: "Primates", ipa: "Pry-maytz", bn: "প্রাইমেট" },
        { w: "Rodents", ipa: "Roh-dents", bn: "ইঁদুর জাতীয় প্রাণী" },
        { w: "Reptile", ipa: "Rep-tyl", bn: "সরীসৃপ" },
        { w: "Insects", ipa: "In-sekts", bn: "পোকামাকড়" },
        { w: "Octopus", ipa: "Ok-tuh-pus", bn: "অক্টোপাস" },
        { w: "Livestock", ipa: "Lyv-stok", bn: "গবাদি পশু" },
        { w: "Creature", ipa: "Kree-cher", bn: "প্রাণী" },
        { w: "Penguin", ipa: "Peng-gwin", bn: "পেঙ্গুইন" },
        { w: "Mushroom", ipa: "Muh-shroom", bn: "মাশরুম" },
        { w: "Fungus", ipa: "Fun-gus", bn: "ছত্রাক" },
        { w: "Leaves", ipa: "Leevz", bn: "পাতা" },
        { w: "Seed", ipa: "Seed", bn: "বীজ" },
        { w: "Trunk", ipa: "Trunk", bn: "কাণ্ড" },
        { w: "Branch", ipa: "Branch", bn: "শাখা" },
        { w: "Cluster", ipa: "Klus-ter", bn: "গুচ্ছ" }
    ],
    // Page 6: Continents, Countries, Cities & Buildings
    [
        { w: "South America", ipa: "South uh-mer-uh-kuh", bn: "দক্ষিণ আমেরিকা" },
        { w: "North America", ipa: "North uh-mer-uh-kuh", bn: "উত্তর আমেরিকা" },
        { w: "Europe", ipa: "Yoor-up", bn: "ইউরোপ" },
        { w: "Australia", ipa: "Aw-stray-lee-uh", bn: "অস্ট্রেলিয়া" },
        { w: "Indonesia", ipa: "In-duh-nee-zhuh", bn: "ইন্দোনেশিয়া" },
        { w: "Switzerland", ipa: "Swit-ser-lund", bn: "সুইজারল্যান্ড" },
        { w: "United Kingdom", ipa: "Yoo-ny-tid king-dum", bn: "যুক্তরাজ্য" },
        { w: "The Philippines", ipa: "Fil-uh-peenz", bn: "ফিলিপাইন" },
        { w: "Lighthouse", ipa: "Lyt-hows", bn: "বাতিঘর" },
        { w: "Duplex", ipa: "Doo-pleks", bn: "ডুপ্লেক্স" },
        { w: "Bungalow", ipa: "Bung-guh-loh", bn: "বাংলো" },
        { w: "Houseboat", ipa: "Hows-boht", bn: "হাউসবোট" },
        { w: "Landlord", ipa: "Land-lord", bn: "বাড়িওয়ালা" },
        { w: "Tenant", ipa: "Ten-unt", bn: "ভাড়াটিয়া" },
        { w: "Suburb", ipa: "Sub-urb", bn: "শহরতলি" },
        { w: "Dormitory", ipa: "Dor-mi-tor-ee", bn: "ছাত্রাবাস" },
        { w: "Central station", ipa: "Sen-trul stay-shun", bn: "কেন্দ্রীয় স্টেশন" },
        { w: "Embassy", ipa: "Em-buh-see", bn: "দূতাবাস" }
    ],
    // Page 7: Workplaces, Ratings, Verbs & Adjectives
    [
        { w: "Colleague", ipa: "Kol-eeg", bn: "সহকর্মী" },
        { w: "Employer", ipa: "Em-ployer", bn: "নিয়োগকর্তা" },
        { w: "Employment", ipa: "Em-ploy-ment", bn: "চাকরি" },
        { w: "Unemployed", ipa: "Un-em-ployd", bn: "বেকার" },
        { w: "Internship", ipa: "In-turn-ship", bn: "ইন্টার্নশিপ" },
        { w: "Reasonable", ipa: "Ree-zuh-nuh-bul", bn: "যুক্তিসঙ্গত" },
        { w: "Satisfactory", ipa: "Sat-is-fak-tuh-ree", bn: "সন্তোষজনক" },
        { w: "Luxurious", ipa: "Lug-zhoor-ee-us", bn: "বিলাসবহুল" },
        { w: "Souvenir", ipa: "Soo-vuh-neer", bn: "স্মারক বস্তু / স্যুভেনির" },
        { w: "Supervise", ipa: "Soo-per-vyz", bn: "তত্ত্বাবধান করা" },
        { w: "Exhibit", ipa: "Ig-zib-it", bn: "প্রদর্শন করা" },
        { w: "Persuade", ipa: "Per-sweyd", bn: "রাজি করানো" },
        { w: "Immigrate", ipa: "Im-i-grayt", bn: "অভিবাসী হওয়া" },
        { w: "Energetic", ipa: "En-er-JET-ik", bn: "প্রাণবন্ত" },
        { w: "Ancient", ipa: "AYN-shunt", bn: "প্রাচীন" },
        { w: "Mandatory", ipa: "MAN-duh-tor-ee", bn: "বাধ্যতামূলক" },
        { w: "Vulnerable", ipa: "VUHL-ner-uh-bul", bn: "সংবেদনশীল / ঝুঁকিপূর্ণ" },
        { w: "Optimistic", ipa: "Op-tuh-MIS-tik", bn: "আশাবাদী" },
        { w: "Spectacular", ipa: "Spek-TAK-yuh-ler", bn: "দর্শনীয়" }
    ],
    // Page 8: Hobbies, Sports, Transportation & Weather
    [
        { w: "Extreme sports", ipa: "Ik-streem sports", bn: "এক্সট্রিম স্পোর্টস" },
        { w: "Paragliding", ipa: "Par-uh-gly-ding", bn: "প্যারাগ্লাইডিং" },
        { w: "Skydiving", ipa: "Sky-dy-ving", bn: "স্কাইডাইভিং" },
        { w: "Bungee jumping", ipa: "Bun-gee jump-ing", bn: "বাঞ্জি জাম্পিং" },
        { w: "White-water rafting", ipa: "Wyt-waw-ter raf-ting", bn: "সাদা জল রাফটিং" },
        { w: "Cylindrical", ipa: "Si-lin-dri-kuhl", bn: "নলাকার" },
        { w: "Measurements", ipa: "Mezh-er-ments", bn: "পরিমাপ" },
        { w: "Altitude", ipa: "AL-ti-tood", bn: "উচ্চতা" },
        { w: "Imperial system", ipa: "im-PEER-ee-ul SIS-tem", bn: "ইম্পেরিয়াল পদ্ধতি" },
        { w: "Metric system", ipa: "MET-rik SIS-tem", bn: "মেট্রিক পদ্ধতি" },
        { w: "Hovercraft", ipa: "Huv-er-kraft", bn: "হোভারক্রাফট" },
        { w: "Hydrofoil", ipa: "Hy-droh-foyl", bn: "হাইড্রোফয়েল" },
        { w: "Hot-air balloon", ipa: "Hot-air buh-loon", bn: "হট-এয়ার বেলুন" },
        { w: "Weather forecast", ipa: "Weth-er for-kast", bn: "আবহাওয়ার পূর্বাভাস" }
    ]
];
